---
name: CI

on:
  pull_request:
    paths:
      - "**/*.sh"
      - "Makefile"
      - ".shellcheckrc"
      - "action.yml"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make lint

  functional:
    name: Functional Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
